### ISSUE TITLE
Support base branch being 'master'?

### ISSUE THREAD

**Issue by theobarberbany** [modularml/stack-pr#14]
I'm trying to understand if stack-pr supports the base branch being 'master' or if it only supports 'main'?

**Comment by ZolotukhinM** [comment]
You can specify the branch name with `-T/--target` option, which defaults to "main" if not specified.

**Comment by ZolotukhinM** [comment]
Note that there was a bug in this feature, but it should be fixed in https://github.com/modularml/stack-pr/pull/13

**Comment by theobarberbany** [comment]
Ah that's great, I'll try with #13  locally. Thanks!
