### ISSUE TITLE
PR description removed on submit?

### ISSUE THREAD

**Issue by drisspg** [modularml/stack-pr#17]
# Summary

If I want to add PR description on markdown in github ui. After I submit a new commit on top of the stack it appears that the description body is scrubbed, is that expected?

**Comment by ZolotukhinM** [comment]
Yes, this is an expected default behavior, but there is an option `--keep-body` if you'd like to change that. If you use that than it will keep the text below `--- --- ---` line in the PR description.

**Comment by drisspg** [comment]
whoops, sorry just seeing that now, one other noob question is there a way to have a globaly defined  dot file for the config options I want to set across repos

**Comment by ZolotukhinM** [comment]
No, but that would be awesome to have! I've been thinking about it, but haven't gotten around to actually implementing it :( PRs will be welcome!

**Comment by drisspg** [comment]
Sounds good thank you!
