### ISSUE TITLE
Feature request: support customized branch names for created PRs

### ISSUE THREAD

**Issue by PeimingLiu** [modularml/stack-pr#18]
Hi,

Seems that stack-pr hardcoded to use `"f{username}/stack/{id}"` for the branch name, but some repos have restriction on the branch name (e.g., [LLVM](https://github.com/llvm/llvm-project/rules/1348?ref=refs%2Fheads%2FPeimingLiu%2Fstack%2F1)). I tried to [use the tool](https://github.com/llvm/llvm-project/pull/105565) but could only get it work by modifying the code myself.

**Comment by ZolotukhinM** [comment]
That sounds like a reasonable feature to have - given that you've already made the changes, would you be able to send a pull request to add this? :)

**Comment by PeimingLiu** [comment]
Guess what, I just hardcoded a different prefix to fit my need too :).

With that being said, I also don't think simply requiring a `--prefix` argument to override the default behavior is ideal either. Maybe it would be better to support a per-project configuration?

**Comment by ZolotukhinM** [comment]
Yeah, we can have something like a branch-name template. E.g. by default it would be `<<USERNAME>>/stack/<<ID>>` (syntax is arbitrary), but then it can be configured to be something else, e.g. `users/<<USERNAME>>/stack/<<ID>>`.
