### ISSUE TITLE
Question: Amending previous commits

### ISSUE THREAD

**Issue by vck3000** [modularml/stack-pr#34]
Hi there,

Nice project!

> If we need to make changes to any of the PRs (e.g. to address the review feedback), we simply amend the desired changes to the appropriate git commits and run submit again. If needed, we can rearrange commits or add new ones.

Simple question, but could you provide some examples on how you would amend a previous commit, and how you would rearrange commits/add new ones? 

In my current workflow, for a particular PR, I would simply push new commits, so I'm not sure the best way to amend something in the past. 

Thanks!

**Comment by AmaranthineCodices** [comment]
Generally you accomplish this by rebasing. An interactive rebase will allow you to edit a given commit or re-order commits arbitrarily (as long as the resulting merge conflicts are resolved). It will also allow insertion of new commits at any point in the stack. Once the rebase is performed, `stack-pr submit` will update any existing PRs on GitHub, as well as create new ones, to reflect the changes made to your local branch.

**Comment by ZolotukhinM** [comment]
@AmaranthineCodices's answer is on point, and I'm going to close this issue. Please feel free to file more issues with questions/bugs/feature requests!

**Comment by vck3000** [comment]
Great, thank you. I will have a read!
