### ISSUE TITLE
confusing order of stacked PRs in PR description

### ISSUE THREAD

**Issue by GiorgosAlexakis** [modularml/stack-pr#41]
Even though the order follows the same pattern as when looking at commits with git log, it may be confusing for reviewers to see stacked PRs in reverse order.

**Comment by GiorgosAlexakis** [comment]
@ZolotukhinM what do you think we should do?

- Keep as is, prefer limited configuration.
- Add a configuration option to select the order of the stacked PRs in description.
- Prefer limited configuration, but switch to 'first to last' ordering.

**Comment by ZolotukhinM** [comment]
It would be confusing to some people no matter which way we choose, and adding an option can made it even more confusing if one has to review stacks from people with different order settings. So far the design principle we've sticked was to mimic what git does, so I'd say we should stick with the current way and don't change it.

**Comment by smudge** [comment]
> It would be confusing to some people no matter which way we choose

Apologies for chiming in a year later, but it occurred to me that in either case this confusion would be resolved if something visual existed to indicate where `main` is in the stack.

Something like:

---

Stacked PRs:

- https://github.com/modular/stack-pr/pull/91
- -> https://github.com/modular/stack-pr/pull/91
- https://github.com/modular/stack-pr/pull/91
- `main`

---

or:

---

Stacked PRs:

- `main`
  - https://github.com/modular/stack-pr/pull/91
    - https://github.com/modular/stack-pr/pull/91 👈  **you are here**
      - https://github.com/modular/stack-pr/pull/91

---

WDYT?
